default:
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
test-job1:
  stage: test
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
    - apk add --no-cache --virtual .build-deps gcc musl-dev \ && pip install --no-cache-dir -r /code/requirements.txt \ && apk del .build-deps
    - pip install paramiko
    - python3 -m unittest -v test/TestStringMethods.py

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
