default:
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
stages:
  - build
  - test
  - deploy
  - delivery
test-job0:
  stage: test
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - files=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
    - echo $files
    - python3 test/linter.py $files || echo $?
test-job1:
  stage: test
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - python3 -m unittest -v TestStringMethods.py
test-job2:
  stage: test
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - coverage run --branch -m unittest -v TestStringMethods.py
    - coverage report -m
  coverage: '/TOTAL.*\s+(\d+\%)/'
deploy-prod:
  stage: deploy
  script:
    - echo "deploy"
  #only:
  #  - master 
  artifacts:
    name: projet
    paths:
      - "/"
    exclude:
      - /__pycache__/
    
delivery-job:
  stage: delivery
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - ls
    - cd projet
    - ls
    

    
    
