default:
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
    - ip a
stages:
  - build
  - test
  - deploy
test-job0:
  stage: test
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
    - pip install pylint
    - apk update && apk add git
    - files=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
    - echo $files
    - python3 test/pylintt.py $files
test-job1:
  stage: test
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
    - apk add gcc python3-dev musl-dev libffi-dev openssl-dev make
    - python3 -m pip install --upgrade pip
    - pip install paramiko
    - python3 -m unittest -v TestStringMethods.py


deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
