stages:
  - build
  - test
  - delivery
default:
  image: group8tse/pipeline_image:latest
  script:
    - echo "Running default"
test-lint:
  stage: test
  #image: group8tse/pipeline_image:latest
  script:
    - files=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
    - echo $files
    - python3 test/linter.py $files || echo $?
test-custom:
  stage: test
  #image: group8tse/pipeline_image:latest
  script:
   - python3 -m unittest -v TestStringMethods.py
test-coverage:
  stage: test
  #image: group8tse/pipeline_image:latest
  script:
    - coverage run --branch -m unittest -v TestStringMethods.py
    - coverage report -m
  coverage: '/TOTAL.*\s+(\d+\%)/'    
delivery-job:
  stage: delivery
  image: docker:19.03.12

  variables:
    CI_REGISTRY: docker.io
    CI_REGISTRY_IMAGE: index.docker.io/$CI_REGISTRY_USER/project_image:latest
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - echo "Deployment- $CI_COMMIT_BRANCH branch."
    - docker build --cache-from "$CI_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  #only:
  #  - feature

    

    
    
