default:
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - python -m unittest discover --verbose -s "TestStringMethods.py"

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
