default:
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
test-job1:
  stage: test
  image: python:3.8-alpine
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
    - apk add gcc python3-dev musl-dev libffi-dev openssl-dev make
    - pip install paramiko
    - python3 -m unittest -v test/TestStringMethods.py

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
