default:
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
stages:
  - build
  - test
  - deploy
  - delivery
test-job0:
  stage: test
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - files=$(git diff-tree --no-commit-id --name-only -r $CI_COMMIT_SHA)
    - echo $files
    - python3 test/linter.py $files || echo $?
test-job1:
  stage: test
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - python3 -m unittest -v TestStringMethods.py
test-job2:
  stage: test
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - coverage run --branch -m unittest -v TestStringMethods.py
    - coverage report -m
  coverage: '/TOTAL.*\s+(\d+\%)/'
#deploy-prod:
#  stage: deploy
#  script:
#    - echo "deploy"
  #only:
  #  - master 
#  artifacts:
#    name: "projet"
#    paths:
#      - "/"
#    exclude:
#      - /__pycache__/
    
delivery-job:
  stage: delivery
  image: docker:19.03.12

  variables:
    CI_REGISTRY_USER: <dockerio-username>
    CI_REGISTRY_PASSWORD: <dockerio-password>
    CI_REGISTRY: docker.io
    CI_REGISTRY_IMAGE: index.docker.io/$CI_REGISTRY_USER/<imagename>
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
      

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - cd /
    - service docker start
    #- containerId=$(docker inspect -f   '{{.Id}}'  SHORT_CONTAINER_ID-or-CONTAINER_NAME)
    - containerId=$(cat /proc/self/cgroup | head -1 | tr --delete ‘10:memory:/docker/’)
    - echo "$containerId"
    - docker cp  $CI_PROJECT_DIR/ $containerId:/projet
    

    

    
    
