default:
  image: rahmouniyoussra/prjtinterface:latest
  script:
    - export http_proxy=http://cache.univ-st-etienne.fr:3128/
    - export https_proxy=http://cache.univ-st-etienne.fr:3128/
    - export ftp_proxy=http://cache.univ-st-etienne.fr:3128/
    - ip a
build-job1:
  stage: build
  script:
    - echo "hello "
